# Create consul configurations

- name: Create configuration
  copy:
    dest: "{{ consul_config_path }}/config.json"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    content: "{{ lookup('template', 'templates/config.json.j2') | to_nice_json }}"
  notify: restart consul

- name: Create custom configuration
  copy:
    dest: "{{ consul_config_path }}/custom_config.json"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    content: "{{ lookup('template', 'templates/custom_config.json.j2') | to_nice_json }}"
  when: consul_config_custom is defined
  notify: restart consul