# Add TLS

- block:
    - name: Create SSL directory
      file:
        dest: "{{ consul_tls_dir }}"
        state: directory
        owner: "{{ consul_user }}"
        group: "{{ consul_group }}"
        mode: 0755
      tags: tls

    - name: Copy CA certificate
      copy:
        remote_src: "{{ consul_tls_files_remote_src }}"
        src: "{{ consul_tls_src_files }}/ca/{{ consul_tls_ca_crt | basename }}"
        dest: "{{ consul_tls_dir }}/{{ consul_tls_ca_crt }}"
        owner: "{{ consul_user }}"
        group: "{{ consul_group }}"
        mode: 0644
      tags: tls

    - name: Copy server certificate
      copy:
        remote_src: "{{ consul_tls_files_remote_src }}"
        src: "{{ consul_tls_src_files }}/server/{{ consul_tls_server_crt | basename }}"
        dest: "{{ consul_tls_dir }}/{{ consul_tls_server_crt }}"
        owner: "{{ consul_user }}"
        group: "{{ consul_group }}"
        mode: 0644
      tags: tls

    - name: Copy server key
      copy:
        remote_src: "{{ consul_tls_files_remote_src }}"
        src: "{{ consul_tls_src_files }}/server/{{ consul_tls_server_key | basename }}"
        dest: "{{ consul_tls_dir }}/{{ consul_tls_server_key }}"
        owner: "{{ consul_user }}"
        group: "{{ consul_group }}"
        mode: 0600
      tags: tls

  when:
    - consul_tls_enable | bool
    - consul_tls_copy_keys | bool
  notify: restart consul