# Add gossip encryption

- block:
    - block:
        - name: Check for gossip encryption key on previously boostrapped server
          command: "cat {{ consul_config_path }}/config.json"
          register: consul_gossip_encryption_key_read

        - name: Save gossip encryption key from existing configuration
          set_fact:
            consul_gossip_encryption_key: "{{ consul_gossip_encryption_key_read.stdout | from_json | json_query(query) }}"
          vars:
            query: "encrypt"
          no_log: true

      run_once: true
      when:
        - consul_gossip_encryption_key is not defined
        - bootstrap_state.stat.exists | bool


    # Generate new key if none was found
    - block:
        - name: Generate gossip encryption key
          shell: "PATH={{ consul_bin_path }}:$PATH consul keygen"
          register: consul_gossip_encryption_keygen

        - name: Save gossip encryption key
          set_fact:
            consul_gossip_encryption_key: "{{ consul_gossip_encryption_keygen.stdout }}"
          no_log: true
          
      run_once: true
      when:
        - (consul_gossip_encryption_key is not defined or consul_gossip_encryption_key | length == 0)
        - not bootstrap_state.stat.exists | bool

    - name: Display Gossip Encryption Key
      debug:
        msg: "{{ consul_gossip_encryption_key }}"
      run_once: true
      when:
        - consul_encrpyt_key_display | bool

  when:
    - consul_encrypt_enable | bool