# Create & verify directories for Consul

- name: Create directories
  block:
  - name: Configuration and data directories
    file:
      dest: "{{ item }}"
      state: directory
      owner: "{{ consul_user }}"
      group: "{{ consul_group }}"
      mode: 0700
    with_items:
      - "{{ consul_dir_path }}"
      - "{{ consul_config_path }}"
      - "{{ consul_data_path }}"
  - name: Run directory
    file:
      dest: "{{ consul_run_path }}"
      state: directory
      owner: "{{ consul_user }}"
      group: "{{ consul_group }}"
      mode: 0750

- name: Create log directory
  file:
    dest: "{{ consul_log_path }}"
    state: directory
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"

- name: Verify binary path
  file:
    path: "{{ consul_bin_path }}"
    state: directory
    owner: root
    mode: 0755