# Add gossip encryption

- block:
    - name: Check for gossip encryption key on previously boostrapped server
      command: "cat {{ consul_config_path }}/config.json"
      register: consul_gossip_encryption_key_read
      run_once: true

    - name: Save gossip encryption key from existing configuration
      set_fact:
        consul_gossip_encryption_key: "{{ consul_gossip_encryption_key_read.stdout | from_json | json_query(query) }}"
      vars:
        query: "encrypt"
        
  when:
    - (consul_gossip_encryption_key is not defined or consul_gossip_encryption_key | trim == '')
    - bootstrap_state.stat.exists | bool

- name: Write gossip encryption key locally for use with new servers
  copy:
    content: "{{ consul_gossip_encryption_key }}"
    dest: /tmp/consul_encrypt.key
  become: no
  when:
    - (consul_gossip_encryption_key is defined or consul_gossip_encryption_key | trim != '')
    - bootstrap_state.stat.exists | bool

- name: Read gossip encryption key for servers that require it
  set_fact:
    consul_gossip_encryption_key: "{{ lookup('file', '/tmp/consul_encrypt.key') }}"
  when:
    - (consul_gossip_encryption_key is not defined and consul_gossip_encryption_key | trim == '')
    - bootstrap_state.stat.exists | bool

- name: Delete gossip encryption key file
  file:
    path: "/tmp/consul_encrypt.key"
    state: absent
  become: no
  when:
    - (consul_gossip_encryption_key is defined and consul_gossip_encryption_key | trim != '')
    - bootstrap_state.stat.exists | bool

- block:
    - name: Generate gossip encryption key
      shell: "PATH={{ consul_bin_path }}:$PATH consul keygen"
      register: consul_keygen
      run_once: true

    - name: Write gossip encryption key to fact
      set_fact: consul_gossip_encryption_key={{ consul_keygen.stdout }}
  when:
    - (consul_gossip_encryption_key is not defined or consul_gossip_encryption_key | trim == '') 
    - not bootstrap_state.stat.exists | bool

- name: Display Gossip Encryption Key
  debug:
    msg: "{{ consul_gossip_encryption_key }}"
  when:
    - (consul_gossip_encryption_key is defined and consul_gossip_encryption_key | trim != '') 
    - consul_encrpyt_key_display | bool
