# Add snapshot for Consul

- name: Create snapshot systemd script
  template:
    src: consul_systemd_snapshot.service.j2
    dest: /lib/systemd/system/consul_snapshot.service
    owner: root
    group: root
    mode: 0644
  register: systemd_unit
  notify: start snapshot
  when:
    - ansible_service_mgr == "systemd"
    - consul_snapshot | bool

- name: Create snaps storage folder
  file:
    state: directory
    path: "{{ consul_snapshot_storage_path }}"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0744

- name: Create snaps storage config folder
  file:
    state: directory
    path: "{{ consul_snapshot_config_path }}"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0744

- name: Create snapshot agent config
  template:
    src: consul_snapshot.json.j2
    dest: "{{ consul_snapshot_config_path }}/consul_snapshot.json"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0644
  notify: start snapshot
  when:
    - ansible_service_mgr == "systemd"
    - consul_snapshot | bool

- name: Reload systemd
  systemd:
    daemon_reload: true
  when: systemd_unit | changed