# Install requirement dependencies

- name: Install python dependencies
  when:
    - consul_install_dependencies | bool
  block:
    - name: Install netaddr dependency on controlling host (with --user)
      pip:
        name: netaddr
        extra_args: --user
      delegate_to: 127.0.0.1
      become: false
      vars:
        ansible_become: false
      run_once: true
      when: not is_virtualenv or is_virtualenv == None

    - name: Install netaddr dependency on controlling host (virtualenv)
      pip:
        name: netaddr
      delegate_to: 127.0.0.1
      become: false
      vars:
        ansible_become: false
      run_once: true
      when: is_virtualenv is defined

- name: Install OS packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ consul_os_packages }}"
  tags: installation