# Install dnsmasq instead than iptables

- name: Check Dnsmasq exist
  stat: 
    path: '/etc/init.d/dnsmasq'
  register: dnsmasq_service
  changed_when: false
  tags: dnsmasq, installation

- name: Install Dnsmasq package
  apt:
    name: dnsmasq
    state: present
  tags: dnsmasq, installation
  when: not dnsmasq_service.stat.exists | bool

- name: Enable dnsmasq service
  service:
    name: dnsmasq
    enabled: true
  tags: dnsmasq
  when: not dnsmasq_service.stat.exists | bool

- name: Create Dnsmasq configuration
  template:
    src: dnsmasq-10-consul.j2
    dest: /etc/dnsmasq.d/10-consul
    owner: root
    group: root
    mode: 0644
  notify: restart dnsmasq
  tags: dnsmasq