# Main tasks for Consul

- name: Verify Debian and other requirements of OS
  import_tasks: verify_os.yml

- name: Include variables
  include_vars: "main.yml"
  tags: always

- name: Prepare install Consul
  import_tasks: prepare_install.yml

- name: Include user and group settings
  import_tasks: add_user_group.yml

- name: Include directory settings
  import_tasks: add_dirs.yml

- name: Install consul
  import_tasks: install_consul.yml
  when:
    - consul_install_binary | bool

- name: Install dnsmasq
  import_tasks: install_dnsmasq.yml

- name: Add gossip encrpytion
  improt_tasks: add_gossip_encryption.yml
  when:
    - consul_encrypt_enable | bool