# Main tasks for Consul

- name: Verify Debian and other requirements of OS
  import_tasks: verify_os.yml

- name: Add variables
  include_vars: "main.yml"
  tags: always

- name: Prepare install Consul
  import_tasks: prepare_install.yml

- name: Add user and group settings
  import_tasks: add_user_group.yml

- name: Add directory settings
  import_tasks: add_dirs.yml

- name: Install consul
  import_tasks: install_consul.yml
  when:
    - consul_install_binary | bool
    
- name: Add gossip encrpytion
  import_tasks: add_gossip_encryption.yml

- name: Add ACL configuration
  import_tasks: add_acl.yml

- name: Add Consul configuration
  import_tasks: add_consul_config.yml

- name: Add TLS
  import_tasks: add_tls.yml

- name: Add Syslog configuration
  import_tasks: add_syslog.yml

- name: Add SystemD for consul script
  import_tasks: add_system_script.yml

- name: Enable Consul Snapshots on servers
  import_tasks: add_snapshot.yml
  when:
    - ansible_service_mgr == "systemd"
    - consul_snapshot | bool

- name: Run consul
  import_tasks: run_consul.yml

- name: Include services management
  import_tasks: services_management.yml
  when: consul_services is defined and consul_services|length>0
  tags:
    - consul_services

- name: flush_handlers
  meta: flush_handlers