- block:
    - name: Start Consul
      service:
        name: consul
        state: started
        enabled: true

    - name: Check Consul HTTP API (via TCP socket)
      wait_for:
        delay: 15
        port: "{{ consul_ports.http|int }}"
        host: "{{ consul_addresses.http }}"
      when: (consul_ports.http|int > -1) and (consul_addresses.http|ipaddr)

    - name: Check Consul HTTP API (via unix socket)
      wait_for:
        delay: 15
        path: "{{ consul_addresses.http | replace('unix://', '', 1) }}"
      when: consul_addresses.http is match("unix://*")

    - name: Create bootstrapped state file
      file:
        dest: "{{ consul_bootstrap_state_path }}"
        state: touch
    
    - include_tasks: install_iptables.yml
      when: consul_iptables_enable | bool

  when: not bootstrap_state.stat.exists

- include_tasks: install_dnsmasq.yml
  when: consul_dnsmasq_enable | bool