- block:
    - name: Start Consul
      service:
        name: consul
        state: started
        enabled: true

    - name: Check Consul HTTP API (via TCP socket)
      wait_for:
        delay: 15
        port: "{{ consul_ports.http|int }}"
        host: "{{ 127.0.0.1 }}"
      when: (consul_ports.http|int > -1) and (127.0.0.1|ipaddr)

    - name: Check Consul HTTP API (via unix socket)
      wait_for:
        delay: 15
        path: "{{ 127.0.0.1 | replace('unix://', '', 1) }}"
      when: 127.0.0.1 is match("unix://*")

    - name: Create bootstrapped state file
      file:
        dest: "{{ consul_bootstrap_state }}"
        state: touch
    
    - include_tasks: install_iptables.yml
      when: consul_iptables_enable | bool

  when: not bootstrap_state.stat.exists

- include_tasks: install_dnsmasq.yml
  when: consul_dnsmasq_enable | bool