- name: restart consul
  service:
    name: consul
    state: restarted
  listen: 'restart consul'

- name: restart dnsmasq
  service:
    name: dnsmasq
    state: restarted
  listen: 'restart dnsmasq'

- name: restart syslog-ng
  service:
    name: syslog-ng
    state: restarted
  listen: 'restart syslog-ng'

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted
  listen: 'restart rsyslog'

- name: start consul
  service:
    name: consul
    state: started
  listen: 'start consul'

- name: start consul snapshot
  service:
    name: consul_snapshot
    state: started
    enabled: true
  listen: 'start snapshot'
