- name: restart consul
  service:
    name: consul
    state: restarted
  listen: 'restart consul'

- name: restart dnsmasq
  service:
    name: dnsmasq
    state: restarted
  listen: 'restart dnsmasq'

- name: start consul
  service:
    name: consul
    state: started
  listen: 'start consul'

- name: start consul snapshot
  service:
    name: consul_snapshot
    state: started
    enabled: true
  listen: 'start snapshot'
