- name: restart consul
  service:
    name: consul
    state: restarted
  listen: 'restart consul'

- name: restart dnsmasq
  service:
    name: dnsmasq
    state: restarted
  listen: 'restart dnsmasq'

- name: reload consul configuration
  command: "pkill --pidfile '{{ consul_run_path }}/consul.pid' --signal SIGHUP"
  listen: 'reload consul configuration'
